export default {
  SET_LOCALE: 'SET_LOCALE',

  GET_TRANSLATIONS_REQUEST: 'GET_TRANSLATIONS_REQUEST',
  GET_TRANSLATIONS_SUCCESS: 'GET_TRANSLATIONS_SUCCESS',
  GET_TRANSLATIONS_FAIL: 'GET_TRANSLATIONS_FAIL',

  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAIL: 'GET_PROJECTS_FAIL',

  PROJECTS_SHOW_GALLERY: 'PROJECTS_SHOW_GALLERY',
  PROJECTS_HIDE_GALLERY: 'PROJECTS_HIDE_GALLERY',

  ADD_ERROR: 'ADD_ERROR',

  ADD_DATA_VERSION: 'ADD_DATA_VERSION'
};
