export default {
  SET_LOCALE: 'SET_LOCALE',
  GET_TRANSLATIONS_REQUEST: 'GET_TRANSLATIONS_REQUEST',
  GET_TRANSLATIONS_SUCCESS: 'GET_TRANSLATIONS_SUCCESS',
  GET_TRANSLATIONS_FAIL: 'GET_TRANSLATIONS_FAIL',
  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAIL: 'GET_PROJECTS_FAIL'
};
