export default {
  SET_LOCALE: 'SET_LOCALE',
  GET_LOCALE_DATA_REQUEST: 'GET_LOCALE_DATA_REQUEST',
  GET_LOCALE_DATA_SUCCESS: 'GET_LOCALE_DATA_SUCCESS',
  GET_LOCALE_DATA_FAIL: 'GET_LOCALE_DATA_FAIL',
  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAIL: 'GET_PROJECTS_FAIL'
};
